### ISSUE TITLE
[BUG]- SFDMU doesn't play well with @salesforce/cli

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#634]
**Describe the bug**

sfdmu does not play well with @salesforce/cli, it seems a hook triggers a crash even when sfdmu is not called

**To Reproduce**

Github Action workflow crashing with sfdmu with hte following error

```sh
2023-09-10T16:06:17.674Z sf:sfdx-hardis:hooks:init TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (/home/runner/.local/share/sf/node_modules/sfdx-hardis/node_modules/@salesforce/core/lib/connection.js:28:48)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/runner/.local/share/sf/node_modules/sfdx-hardis/node_modules/@salesforce/core/lib/authInfo.js:25:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

```yaml
# Add your major branches names here
# If you do, also add SFDX_CLIENT_ID / KEY variables in job step "Login & Process Deployment" below
on:
  push:
    branches:
      - main
      - preprod
      - uat
      - integration

name: Process Deployment (sfdx-hardis)

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  process_deployment:
    name: Process Deployment to Major Org
    runs-on: ubuntu-latest
    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Faster code checkout fetching only latest commit
    # Setup node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    # SFDX & plugins
    - name: Install SFDX and plugins
      run: |
        npm install @salesforce/cli --global
        sf plugins install @salesforce/plugin-packaging
        echo 'y' | sfdx plugins:install sfdx-hardis
        echo 'y' | sfdx plugins:install sfdx-essentials
        echo 'y' | sfdx plugins:install sfdmu # Disabled while it does not play well with @salesforce/cli
        echo 'y' | sfdx plugins:install sfdx-git-delta
        sf version --verbose --json
    # Set env branch variable (github.ref_name seems to not work)
    - name: Set env.BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    # Login & check deploy with test classes & code coverage
    - name: Login & Process Deployment
      env:
        SFDX_CLIENT_ID_INTEGRATION: ${{ secrets.SFDX_CLIENT_ID_INTEGRATION}}
        SFDX_CLIENT_KEY_INTEGRATION: ${{ secrets.SFDX_CLIENT_KEY_INTEGRATION}}
        SFDX_CLIENT_ID_UAT: ${{ secrets.SFDX_CLIENT_ID_UAT}}
        SFDX_CLIENT_KEY_UAT: ${{ secrets.SFDX_CLIENT_KEY_UAT}}
        SFDX_CLIENT_ID_PREPROD: ${{ secrets.SFDX_CLIENT_ID_PREPROD}}
        SFDX_CLIENT_KEY_PREPROD: ${{ secrets.SFDX_CLIENT_KEY_PREPROD}}
        SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
        SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
        SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
        SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
        CI_COMMIT_REF_NAME: ${{ env.BRANCH }} # Defines the target branch of the PR
        ORG_ALIAS: ${{ env.BRANCH }} # Defines the target branch of the PR
        CONFIG_BRANCH: ${{ env.BRANCH }} # Defines the target branch of the PR
        FORCE_COLOR: "1"
      run: |
        echo "Process SFDX deployment using Hardis against \"$CONFIG_BRANCH\""
        sfdx hardis:auth:login
        sfdx hardis:project:deploy:sources:dx
```

Github Workflow not crashing without sfdmu

```yaml
# Add your major branches names here
# If you do, also add SFDX_CLIENT_ID / KEY variables in job step "Login & Process Deployment" below
on:
  push:
    branches:
      - main
      - preprod
      - uat
      - integration

name: Process Deployment (sfdx-hardis)

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  process_deployment:
    name: Process Deployment to Major Org
    runs-on: ubuntu-latest
    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Faster code checkout fetching only latest commit
    # Setup node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    # SFDX & plugins
    - name: Install SFDX and plugins
      run: |
        npm install @salesforce/cli --global
        sf plugins install @salesforce/plugin-packaging
        echo 'y' | sfdx plugins:install sfdx-hardis
        echo 'y' | sfdx plugins:install sfdx-essentials
        # echo 'y' | sfdx plugins:install sfdmu # Disabled while it does not play well with @salesforce/cli
        echo 'y' | sfdx plugins:install sfdx-git-delta
        sf version --verbose --json
    # Set env branch variable (github.ref_name seems to not work)
    - name: Set env.BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    # Login & check deploy with test classes & code coverage
    - name: Login & Process Deployment
      env:
        SFDX_CLIENT_ID_INTEGRATION: ${{ secrets.SFDX_CLIENT_ID_INTEGRATION}}
        SFDX_CLIENT_KEY_INTEGRATION: ${{ secrets.SFDX_CLIENT_KEY_INTEGRATION}}
        SFDX_CLIENT_ID_UAT: ${{ secrets.SFDX_CLIENT_ID_UAT}}
        SFDX_CLIENT_KEY_UAT: ${{ secrets.SFDX_CLIENT_KEY_UAT}}
        SFDX_CLIENT_ID_PREPROD: ${{ secrets.SFDX_CLIENT_ID_PREPROD}}
        SFDX_CLIENT_KEY_PREPROD: ${{ secrets.SFDX_CLIENT_KEY_PREPROD}}
        SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
        SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
        SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
        SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
        CI_COMMIT_REF_NAME: ${{ env.BRANCH }} # Defines the target branch of the PR
        ORG_ALIAS: ${{ env.BRANCH }} # Defines the target branch of the PR
        CONFIG_BRANCH: ${{ env.BRANCH }} # Defines the target branch of the PR
        FORCE_COLOR: "1"
      run: |
        echo "Process SFDX deployment using Hardis against \"$CONFIG_BRANCH\""
        sfdx hardis:auth:login
        sfdx hardis:project:deploy:sources:dx
```

**Expected behavior**

No crash ^^

**export.json**

Unapplicable

**Log file**

with sfdmu installed -> https://github.com/nvuillam/demo-salesforce-ci/actions/runs/6138154545/job/16654755656
without sfdmu installed -> https://github.com/nvuillam/demo-salesforce-ci/actions/runs/6138398746/job/16655256589

**_target.csv** file.

Not applicable
